### ISSUE TITLE
Should not fail if only Driver Station or Robot Controller installed

### ISSUE THREAD

**Issue by gorpong** [dc74089/Tesla-Inspect#2]
Great program, thanks!

In all of the documentation, FIRST states very specifically that you should NOT have both the Driver Station and the Robot Controller on the same phone.  Given that, having the program show a FAIL if you don't have them both installed is an incorrect assessment.

You might want to have it only FAIL if _both_ of them are missing, not just one of them.

**Comment by dc74089** [comment]
The app currently looks at your phone's WiFi Direct name to determine its role (driver station or robot controller) and evaluates the apps installed based on that. For example, a phone named 9277-RC would pass if it had the robot controller app and channel changer app installed, regardless of whether the driver station app was installed or not. The UI doesn't make this clear, some extra logic to only show what it's checking for is in the works, so I'll keep this issue open until I finish that.

**Comment by gorpong** [comment]
Possibly, but my name is definitely 8424-B-RC and it's giving me an
error and saying I "Failed" because I'm not also having the Driver
Station installed.

**Comment by dc74089** [comment]
Hmm. That's definitely a bug. I'll look into that.

**Comment by gorpong** [comment]
I see what the problem is now.  It's NOT that it's finding the robot
controller and not the driver station, it's that we're using AppInventor
and the name of the application is NOT FTCRobot Controller, but the name
of the app that we've defined in AppInventor (in this case it's
EncoderTest).   The team I coach uses different AppInventor projects for
different aspects, so they know which one of the apps they're dealing
with in their testing.

Found it when I installed Tesla Inspect on the driver station and it passed.

I doubt there's any way you can figure out what a team might have named
their FtcRobotController if they're using AppInventor so this is
probably an edge case that you don't need to worry about.

Great job on the app!

```
    -- Gordon.
```

**Comment by dc74089** [comment]
Sweet! I'd still like to investigate if there's a fix for teams using appinventor, could you see if you can find what the fully qualified package name of your robot controller app is? Should be something along the lines of `com.publisher.appname`.
