### ISSUE TITLE
Awesome app!  How about software versions...?

### ISSUE THREAD

**Issue by pmichaud** [dc74089/Tesla-Inspect#4]
This is an incredibly good idea -- thanks for making it available.

Would it be possible for the app to display the version(s) of the robot controller or driver station apps installed on the device, instead of a simple checkmark?  I'm referring primarily to the versions displayed in the "About" screens for each app (currently 1.5).

Again, this is a fantastic app!

Pm
- Coach, FTC #7172 "Technical Difficulties", Plano TX

**Comment by dc74089** [comment]
This is on our roadmap for the next release. Thanks for your input!

**Comment by dc74089** [comment]
Just implemented. Should be released within the week.
